use lab09

CREATE TABLE TB_CLIENTE (
  CD_CLIENTE INT NOT NULL PRIMARY KEY,
  NM_CLIENTE VARCHAR(60) NOT NULL,
  CPF INT NULL,
  DT_NASCIMENTO DATETIME,
  TIPO_CLIENTE VARCHAR(40) NULL
)

INSERT INTO TB_CLIENTE VALUES(1,'JOAO',5444,'19760812',NULL)
INSERT INTO TB_CLIENTE VALUES(2,'CARLOS',3333,'19780812',NULL)
INSERT INTO TB_CLIENTE VALUES(3,'PATRICIA',6666,'19800712',NULL)

DELETE FROM TB_CLIENTE
SELECT * FROM TB_CLIENTE

CREATE TABLE TB_CONTA (
   NR_CONTA INT NOT NULL PRIMARY KEY,
   CD_CLIENTE INT NOT NULL,
   SALDO NUMERIC(10,2) NOT NULL,
)

INSERT INTO TB_CONTA VALUES(100, 1, 12000)
INSERT INTO TB_CONTA VALUES(200, 2, 2000)
INSERT INTO TB_CONTA VALUES(300, 2, 4000)
INSERT INTO TB_CONTA VALUES(400, 2, 1000)
INSERT INTO TB_CONTA VALUES(500, 3, 6000)

SELECT * FROM TB_CONTA

CREATE PROCEDURE SP_CLASSIFICA_CLIENTE(@DATA DATETIME,@QUANTIDADE INT, @CLASSIFICADO VARCHAR(10) OUTPUT)

AS

BEGIN

	IF @DATA >= '2018-03-01' OR @QUANTIDADE > 50

		SET @CLASSIFICADO = 'PARCEIRO'

	ELSE 

		SET @CLASSIFICADO = 'ALVO'

END


CREATE PROCEDURE SP_COPIA_CLIENTE

AS

BEGIN

	DECLARE @DT_INCLUSAO DATETIME;

	DECLARE @QUANTIDADE INT;

	DECLARE @NM_CLIENTE VARCHAR(60);

	DECLARE @CPF INT;

	DECLARE @CD_CLIENTE INT;

	DECLARE @TIPO VARCHAR(10);

	

	DECLARE C_CLIENTE CURSOR FOR

    SELECT 

		TC.CD_CLIENTE,

		TC.NM_CLIENTE ,

		TC.DT_INCLUSAO,

		TC.CPF,

		TV.QUANTIDADE 

	FROM 

		TB_CLIENTE TC

	JOIN

		TB_VENDAS TV ON TC.CD_CLIENTE = TV.CD_CLIENTE  



    OPEN C_CLIENTE;



    FETCH NEXT FROM C_CLIENTE INTO @CD_CLIENTE,@NM_CLIENTE,@DT_INCLUSAO,@CPF,@QUANTIDADE;



    WHILE @@FETCH_STATUS = 0

    BEGIN 

        EXEC SP_CLASSIFICA_CLIENTE @DT_INCLUSAO, @QUANTIDADE, @TIPO OUTPUT 

        IF @TIPO = 'PARCEIRO'

        BEGIN

	        INSERT INTO TB_CLIENTE_PARCEIRO (CD_CLIENTE, NM_CLIENTE, CPF, DT_INCLUSAO)

	        VALUES(@CD_CLIENTE,@NM_CLIENTE,@CPF,@DT_INCLUSAO)

	    END

	    IF @TIPO = 'ALVO'

	    BEGIN

		    INSERT INTO TB_CLIENTE_ALVO (CD_CLIENTE, NM_CLIENTE, CPF, DT_INCLUSAO)

	        VALUES(@CD_CLIENTE,@NM_CLIENTE,@CPF,@DT_INCLUSAO)

	    END    

        

        FETCH NEXT FROM C_CLIENTE INTO @CD_CLIENTE,@NM_CLIENTE,@DT_INCLUSAO,@CPF,@QUANTIDADE;

    END



    CLOSE C_CLIENTE;

    DEALLOCATE C_CLIENTE;

END
