CREATE DATABASE EX07;

USE EX07;


--1
CREATE PROCEDURE SP_AUMENTOSALARIO(@ANO INT, @SALARIO_ATUAL DECIMAL(10,2),@SALARIO_NOVO DECIMAL(10,2) OUTPUT)
AS
BEGIN
	IF @ANO < 2010
	BEGIN 
		SET @SALARIO_NOVO = @SALARIO_ATUAL * 1.3;
	END
	ELSE IF @ANO < 2015
	BEGIN 
		SET @SALARIO_NOVO = @SALARIO_ATUAL * 1.2;
	END
	ELSE
	BEGIN
		SET @SALARIO_NOVO = @SALARIO_ATUAL * 1.1;
	END
END

--2
CREATE TABLE TB_FUNCIONARIO(
	MATRICULA	INT		PRIMARY KEY,
	NM_FUNCIONARIO	VARCHAR(60),
	ANO_ADMISSAO INT,
	SALARIO DECIMAL(10,2)
)

CREATE PROCEDURE SP_ADDFUNCIONARIO(@MATRICULA INT,@NM_FUNCIONARIO VARCHAR(60),@ANO_ADMISSAO INT,@SALARIO DECIMAL(10,2))
AS
BEGIN
	INSERT INTO TB_FUNCIONARIO(MATRICULA,NM_FUNCIONARIO,ANO_ADMISSAO,SALARIO)
	VALUES(@MATRICULA,@NM_FUNCIONARIO,@ANO_ADMISSAO,@SALARIO)
END

--3
CREATE OR ALTER PROCEDURE SP_ATUALIZARSALARIO
AS
BEGIN
	DECLARE @MATRICULA INT;
	DECLARE @ANO INT;
	DECLARE @SALARIO DECIMAL(10,2);
	DECLARE @SALARIO_NOVO DECIMAL(10,2);
	
	DECLARE FUNCIONARIO_CURSOR CURSOR FOR
	SELECT MATRICULA,ANO_ADMISSAO,SALARIO
	FROM TB_FUNCIONARIO;

	OPEN FUNCIONARIO_CURSOR;

	FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @MATRICULA,@ANO,@SALARIO;
	
	WHILE @@FETCH_STATUS = 0
	BEGIN 
		EXEC SP_AUMENTOSALARIO @ANO,@SALARIO,@SALARIO_NOVO OUTPUT 
		UPDATE TB_FUNCIONARIO
		SET SALARIO = @SALARIO_NOVO
		WHERE MATRICULA = @MATRICULA
		FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @MATRICULA,@ANO,@SALARIO;
	END
	CLOSE FUNCIONARIO_CURSOR;
    DEALLOCATE FUNCIONARIO_CURSOR;
END

EXEC SP_ATUALIZARSALARIO





