CREATE DATABASE DB_PROVA02_2024;

USE DB_PROVA02_2024;


--2

CREATE TABLE TB_PRODUTO(
    COD_PRODUTO INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
    DECRICAO VARCHAR(45) NOT NULL ,
    CATEGORIA VARCHAR(45) NOT NULL,
    SUBCATEGORIA VARCHAR(45),
    VALOR DECIMAL(10,2) CHECK (VALOR > 0 AND VALOR IS NOT NULL)
);

CREATE TABLE TB_VENDAS(
    COD_VENDA INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
    DT_VENDA DATE NOT NULL,
    VALOR_UNITARIO DECIMAL(10,2),
    QUANTIDADE INT,
    VALOR_TOTAL AS (QUANTIDADE * VALOR_UNITARIO) PERSISTED,
    COD_PRODUTO INT NOT NULL,
    FOREIGN KEY (COD_PRODUTO) REFERENCES TB_PRODUTO
);

INSERT INTO TB_PRODUTO (DECRICAO, CATEGORIA, SUBCATEGORIA, VALOR) VALUES
('Produto A', 'informatica', 'Subcategoria 1', 10.00),
('Produto B', 'informatica', 'Subcategoria 2', 20.00),
('Produto C', 'Categoria 2', 'Subcategoria 3', 30.00),
('Produto D', 'Categoria 2', NULL, 40.00),  -- Sem subcategoria
('Produto E', 'papelaria', 'Subcategoria 4', 50.00);

INSERT INTO TB_VENDAS (DT_VENDA, VALOR_UNITARIO, QUANTIDADE, COD_PRODUTO) VALUES
('2023-02-01', 10.00, 1, 1),  -- Produto A
('2023-02-02', 20.00, 2, 2),  -- Produto B
('2025-02-03', 30.00, 3, 3),  -- Produto C
('2025-02-04', 40.00, 4, 4),  -- Produto D (sem subcategoria)
('2025-02-05', 50.00, 5, 1);  -- Produto A

--3
--A
SELECT
    COD_PRODUTO,
    DECRICAO
FROM
    TB_PRODUTO
WHERE
    SUBCATEGORIA IS NULL

--B
SELECT
    COD_PRODUTO,
    DECRICAO,
    CATEGORIA
FROM
    TB_PRODUTO
WHERE
    CATEGORIA = 'informatica' or CATEGORIA = 'papelaria'

--C
SELECT
    COD_VENDA,
    DECRICAO,
    QUANTIDADE,
    VALOR_TOTAL
FROM
    TB_VENDAS
JOIN
    TB_PRODUTO TP on TP.COD_PRODUTO = TB_VENDAS.COD_PRODUTO
WHERE
    YEAR(DT_VENDA) = 2023

--D
SELECT
    DECRICAO,
    VALOR_TOTAL
FROM
    TB_VENDAS
JOIN
    TB_PRODUTO TP on TP.COD_PRODUTO = TB_VENDAS.COD_PRODUTO

--E
SELECT
    CATEGORIA,
    VALOR_TOTAL
FROM
    TB_VENDAS
RIGHT JOIN
    TB_PRODUTO TP on TP.COD_PRODUTO = TB_VENDAS.COD_PRODUTO





