/* Esse Script cria um esquema de dados (banco de dados) para controlar
   os bugs encontrados em m�dulos de projetos de Inform�tica dentro de uma empresa.
   No esquema temos as seguintes tabelas:
   TB_CARGO 		-  armazena os diversos cargos dos funcion�rios. 
   TB_FUNCIONARIO 	-  armazena os funcion�rios da empresa.
   TB_PROJETO           -  Cadastro dos Projetos da Empresa.
   TB_MODULO            -  Cadastro dos M�dulos de Cada Projeto. Um Projeto projeto pode
                           ter N M�dulos. Um M�dulo est� associado a apenas um Projeto.
   TB_BUGS              -  Armazena os BUGS que os funcion�rios (Analistas, Programadores ou Gerentes)
                           encontram ao testar M�dulos dos Projetos. Cada BUG � cadastrado por
                           um Funcion�rio e est� ligado a um M�dulo de Projeto. Todo Bug possui
                           um C�digo, uma Descri��o, uma Data de Notifica��o (Data em que foi 
                           cadastrado, e uma Data (DT_Resolvido) que informa a data em que o 
                           BUG foi corrigido. No momento de cadastro do BUG, DT_Resolvido possui
                           o valor NULL. */

CREATE DATABASE lab06

use lab06
   
DROP TABLE TB_BUGS
DROP TABLE TB_FUNCIONARIO
DROP TABLE TB_MODULO
DROP TABLE TB_CARGO
DROP TABLE TB_PROJETO


-- Tabela de Cargo

CREATE TABLE TB_CARGO (
   CD_CARGO INT NOT NULL PRIMARY KEY,
   NM_CARGO VARCHAR(70) NOT NULL
)

INSERT INTO TB_CARGO VALUES (100,'ANALISTA')
INSERT INTO TB_CARGO VALUES (200,'PROGRAMADOR')
INSERT INTO TB_CARGO VALUES (300,'GERENTE')

CREATE TABLE TB_FUNCIONARIO (
 CD_FUNCIONARIO INT NOT NULL PRIMARY KEY,
 NM_FUNCIONARIO VARCHAR(60) NOT NULL,
 CD_CARGO INT NULL,
 SITUACAO VARCHAR(30) NOT NULL CHECK (SITUACAO IN ('ATIVO','INATIVO'))
)

ALTER TABLE TB_FUNCIONARIO ADD CONSTRAINT FK_CD_CARGO
FOREIGN KEY (CD_CARGO) REFERENCES TB_CARGO (CD_CARGO)

INSERT INTO TB_FUNCIONARIO VALUES(1, 'JOAO', 100, 'ATIVO')
INSERT INTO TB_FUNCIONARIO VALUES(2, 'CARLO', 200, 'ATIVO')
INSERT INTO TB_FUNCIONARIO VALUES(3, 'JOANA', 100, 'INATIVO')
INSERT INTO TB_FUNCIONARIO VALUES(4, 'RAFAEL', 100, 'ATIVO')


CREATE TABLE TB_PROJETO (
   CD_PROJETO INT NOT NULL PRIMARY KEY,
   NM_PROJETO VARCHAR(60) NOT NULL,
   DT_INICIO DATETIME NOT NULL,
   DT_FIM DATETIME NULL
)

INSERT INTO TB_PROJETO VALUES(10, 'MATRICULA ONLINE','20190101', '20190601')
INSERT INTO TB_PROJETO VALUES(20, 'WEB AULA','20190401', '20190531')
INSERT INTO TB_PROJETO VALUES(30, 'BIBLIOTECA ONLINE','20190101', NULL)

CREATE TABLE TB_MODULO (
   CD_MODULO INT NOT NULL PRIMARY KEY,
   NM_MODULO VARCHAR(60) NOT NULL,
   CD_PROJETO INT NOT NULL
)

ALTER TABLE TB_MODULO ADD CONSTRAINT FK_CD_PROJETO
FOREIGN KEY (CD_PROJETO) REFERENCES TB_PROJETO (CD_PROJETO)

INSERT INTO TB_MODULO VALUES(1, 'CADASTROS', 10)
INSERT INTO TB_MODULO VALUES(2, 'RELATORIOS', 10)

INSERT INTO TB_MODULO VALUES(3, 'MATERIAL', 20)
INSERT INTO TB_MODULO VALUES(4, 'CHAT', 20)

INSERT INTO TB_MODULO VALUES(5, 'PESQUISA', 30)
INSERT INTO TB_MODULO VALUES(6, 'RESERVA', 30)


CREATE TABLE TB_BUGS (
    CD_BUG INT NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(80) NOT NULL,
    DT_NOTIFICACAO DATETIME NOT NULL,
    DT_RESOLVIDO DATETIME NULL,
    CD_MODULO INT NOT NULL,   
    CD_FUNCIONARIO INT NOT NULL
)


ALTER TABLE TB_BUGS ADD CONSTRAINT FK_CD_MODULO
FOREIGN KEY (CD_MODULO) REFERENCES TB_MODULO (CD_MODULO)

ALTER TABLE TB_BUGS ADD CONSTRAINT FK_CD_FUNCIONARIO
FOREIGN KEY (CD_FUNCIONARIO) REFERENCES TB_FUNCIONARIO(CD_FUNCIONARIO)

INSERT INTO TB_BUGS (CD_BUG, DESCRICAO, DT_NOTIFICACAO, DT_RESOLVIDO, CD_MODULO, CD_FUNCIONARIO)
VALUES (1, 'CAMPO PEQUENO PARA VALOR', '20190201',NULL,1, 1)

INSERT INTO TB_BUGS (CD_BUG, DESCRICAO, DT_NOTIFICACAO, DT_RESOLVIDO, CD_MODULO, CD_FUNCIONARIO)
VALUES (2, 'EXCECAO NAO TRATADA', '20190301',NULL,2, 2)

INSERT INTO TB_BUGS (CD_BUG, DESCRICAO, DT_NOTIFICACAO, DT_RESOLVIDO, CD_MODULO, CD_FUNCIONARIO)
VALUES (3, 'SQL INCORRETO', '20190410',NULL,4, 3)

INSERT INTO TB_BUGS (CD_BUG, DESCRICAO, DT_NOTIFICACAO, DT_RESOLVIDO, CD_MODULO, CD_FUNCIONARIO)
VALUES (4, 'SQL INCORRETO', '20190410',NULL,4, 2)

INSERT INTO TB_BUGS (CD_BUG, DESCRICAO, DT_NOTIFICACAO, DT_RESOLVIDO, CD_MODULO, CD_FUNCIONARIO)
VALUES (5, 'ERRO DE ACESSO A DADOS', '20190510', '20190511',5, 3)

SELECT * FROM TB_BUGS;

SELECT * FROM TB_CARGO;

SELECT * FROM TB_FUNCIONARIO;

SELECT * FROM TB_MODULO;

SELECT * FROM TB_PROJETO;

--1
SELECT 
    fun.NM_FUNCIONARIO AS 'Funcionário',
    car.NM_CARGO AS 'Cargo'
FROM
    TB_FUNCIONARIO fun
JOIN
    TB_CARGO car ON car.CD_CARGO = fun.CD_CARGO
WHERE
    fun.SITUACAO = 'ATIVO'
    AND car.NM_CARGO IN ('ANALISTA', 'PROGRAMADOR');

--2

SELECT
	pjt.NM_PROJETO as 'Projeto',
    mol.NM_MODULO as 'Módulo',
    bug.DESCRICAO as 'Descrição',
    bug.DT_NOTIFICACAO as 'Notificação'
FROM 
	TB_PROJETO pjt
JOIN
	TB_MODULO mol ON (mol.CD_PROJETO = pjt.CD_PROJETO)
JOIN
	TB_BUGS bug on (bug.CD_MODULO = mol.CD_MODULO)

--3
SELECT 
	fun.NM_FUNCIONARIO as 'Funcionário',
    car.NM_CARGO as 'Cargo',
    COUNT(bug.CD_FUNCIONARIO) as 'Quantidade de bugs'
FROM 
	TB_BUGS bug
JOIN
	TB_FUNCIONARIO fun ON (fun.CD_FUNCIONARIO = bug.CD_FUNCIONARIO)
JOIN
	TB_CARGO car on (car.CD_CARGO = fun.CD_CARGO)
GROUP by 
 	fun.NM_FUNCIONARIO,car.NM_CARGO

--4
SELECT 
	fun.NM_FUNCIONARIO as 'Funcionário',
    car.NM_CARGO as 'Cargo',
    COUNT(bug.DESCRICAO) as 'Quantidade de bugs'
FROM 
	TB_BUGS bug
JOIN
	TB_FUNCIONARIO fun ON (fun.CD_FUNCIONARIO = bug.CD_FUNCIONARIO)
JOIN
	TB_CARGO car on (car.CD_CARGO = fun.CD_CARGO)
WHERE
	fun.situacao = 'ATIVO'
GROUP by 
 	fun.NM_FUNCIONARIO,car.NM_CARGO

--5
SELECT
	pjt.NM_PROJETO,
    pjt.DT_INICIO,
    COUNT(bug.CD_BUG) as 'Quantidade de bugs'
FROM 
	TB_PROJETO pjt
left JOIN
	TB_MODULO mod on (mod.CD_PROJETO = pjt.CD_PROJETO)
left JOIN
	TB_BUGS bug on (bug.CD_MODULO = mod.CD_MODULO)
GROUP by 
 	pjt.NM_PROJETO,pjt.DT_INICIO

--6

SELECT
	pjt.NM_PROJETO,
    pjt.DT_INICIO,
    COUNT(bug.CD_BUG) as 'Quantidade de bugs'
FROM 
	TB_PROJETO pjt
left JOIN
	TB_MODULO mod on (mod.CD_PROJETO = pjt.CD_PROJETO)
left JOIN
	TB_BUGS bug on (bug.CD_MODULO = mod.CD_MODULO)
GROUP by 
 	pjt.NM_PROJETO,pjt.DT_INICIO
HAVING
	COUNT(bug.CD_BUG) > 1 and COUNT(bug.CD_BUG) < 10
