use EX09

CREATE TABLE TB_CLIENTE (
  CD_CLIENTE INT NOT NULL PRIMARY KEY,
  NM_CLIENTE VARCHAR(60) NOT NULL,
  CPF INT NULL,
  DT_NASCIMENTO DATETIME,
  TIPO_CLIENTE VARCHAR(40) NULL
)

INSERT INTO TB_CLIENTE VALUES(1,'JOAO',5444,'19760812',NULL)
INSERT INTO TB_CLIENTE VALUES(2,'CARLOS',3333,'19780812',NULL)
INSERT INTO TB_CLIENTE VALUES(3,'PATRICIA',6666,'19800712',NULL)

DELETE FROM TB_CLIENTE
SELECT * FROM TB_CLIENTE

SELECT * FROM TB_CONTA

CREATE TABLE TB_CONTA (
   NR_CONTA INT NOT NULL PRIMARY KEY,
   CD_CLIENTE INT NOT NULL,
   SALDO NUMERIC(10,2) NOT NULL,
)

INSERT INTO TB_CONTA VALUES(100, 1, 12000)
INSERT INTO TB_CONTA VALUES(200, 2, 2000)
INSERT INTO TB_CONTA VALUES(300, 2, 4000)
INSERT INTO TB_CONTA VALUES(400, 2, 1000)
INSERT INTO TB_CONTA VALUES(500, 3, 6000)

CREATE OR ALTER PROCEDURE SP_CLASSIFICA_CLIENTE(@QUANTIDADE INT, @SALDOTOT NUMERIC(10,2),@TIPO VARCHAR(7) OUTPUT )
AS
BEGIN
    IF @SALDOTOT >= 10000 OR @SALDOTOT >= 5000 AND @SALDOTOT < 10000 AND @QUANTIDADE > 2
        SET @TIPO = 'VIP';
    ELSE
        SET @TIPO = 'NORMAL';
end



CREATE OR ALTER PROCEDURE SP_ATUALIZA_TIPO_CLIENTE
AS
BEGIN
    DECLARE @COD INT,@QUANTIDADE INT, @SALDOTOT NUMERIC(10,2),@TIPO VARCHAR(7)

    DECLARE  C_CLIENTE CURSOR FOR
        SELECT
            TB_CLIENTE.CD_CLIENTE,
            COUNT(TB_CLIENTE.CD_CLIENTE),
            SUM(TC.SALDO)
        FROM
            TB_CLIENTE
        JOIN
            TB_CONTA TC on TB_CLIENTE.CD_CLIENTE = TC.CD_CLIENTE
        GROUP BY
            TB_CLIENTE.CD_CLIENTE,NM_CLIENTE

        OPEN C_CLIENTE
        FETCH NEXT FROM C_CLIENTE INTO @COD,@QUANTIDADE,@SALDOTOT;

        WHILE @@FETCH_STATUS = 0
        BEGIN
            EXEC SP_CLASSIFICA_CLIENTE @QUANTIDADE,@SALDOTOT,@TIPO OUTPUT

            UPDATE TB_CLIENTE
            SET TIPO_CLIENTE = @TIPO
            WHERE CD_CLIENTE = @COD

            FETCH NEXT FROM C_CLIENTE INTO @COD,@QUANTIDADE,@SALDOTOT;
        end
end

EXEC SP_ATUALIZA_TIPO_CLIENTE