CREATE DATABASE AV24;

USE AV24;

CREATE TABLE TB_SOLICITACAO_ABERTURA_CONTA(
    ID_SOLICITACAO INT            NOT NULL IDENTITY (1,1) PRIMARY KEY,
    NOME           VARCHAR(100)   NOT NULL,
    CPF            VARCHAR(20)    NOT NULL,
    EMAIL          VARCHAR(100)   NOT NULL,
    RENDA_MENSAL   NUMERIC(10, 2) NULL,
    TELEFONE       VARCHAR(20)    NULL,
    STATUS         VARCHAR(20) DEFAULT ('EM CADASTRO')
        CHECK ( STATUS IN ('EM CADASTRO', 'EM ANALISE',
                           'REPROVADA', 'APROVADA'))
)

CREATE TABLE TB_CLIENTE(
    ID_CLIENTE   INT            NOT NULL IDENTITY (1,1) PRIMARY KEY,
    NOME         VARCHAR(100)   NOT NULL,
    CPF          VARCHAR(20)    NOT NULL UNIQUE,
    EMAIL        VARCHAR(100)   NOT NULL,
    RENDA_MENSAL NUMERIC(10, 2) NOT NULL,
    TELEFONE     VARCHAR(20)    NOT NULL
)

CREATE TABLE TB_CONTA(
    ID_CONTA    INT            NOT NULL IDENTITY PRIMARY KEY,
    ID_CLIENTE  INT            NOT NULL REFERENCES TB_CLIENTE (ID_CLIENTE),
    DT_ABERTURA DATETIME DEFAULT (GETDATE()),
    SALDO       NUMERIC(10, 2) NOT NULL,
    STATUS      VARCHAR(10) CHECK (STATUS IN ('ATIVA', 'BLOQUEADA'))
)

CREATE OR ALTER TRIGGER TG_SOLICITACAO_INSERT_UPDATE
ON TB_SOLICITACAO_ABERTURA_CONTA
AFTER INSERT, UPDATE
AS
BEGIN
    DECLARE @ID_SOLICITACAO INT;
    DECLARE @NOME           VARCHAR(100);
    DECLARE @CPF            VARCHAR(20);
    DECLARE @EMAIL          VARCHAR(100);
    DECLARE @RENDA_MENSAL   NUMERIC(10, 2);
    DECLARE @TELEFONE       VARCHAR(20);
    DECLARE @STATUS         VARCHAR(20);
    DECLARE @ID_CLIENTE     INT;

    DECLARE C_CLIENTE CURSOR FOR
    SELECT ID_SOLICITACAO,NOME,CPF,EMAIL,RENDA_MENSAL,TELEFONE,STATUS
    FROM inserted

    OPEN C_CLIENTE
    FETCH C_CLIENTE INTO @ID_SOLICITACAO,@NOME,@CPF,@EMAIL,@RENDA_MENSAL,@TELEFONE,@STATUS;

    WHILE(@@FETCH_STATUS = 0)
    BEGIN
        IF @RENDA_MENSAL IS NOT NULL AND @TELEFONE IS NOT NULL
        BEGIN
            UPDATE TB_SOLICITACAO_ABERTURA_CONTA
            SET STATUS = 'EM ANALISE'
            WHERE ID_SOLICITACAO = @ID_SOLICITACAO
        end


       IF @STATUS = 'APROVADA'
        BEGIN
            IF(SELECT ID_CLIENTE FROM TB_CLIENTE WHERE CPF = @CPF) IS NULL
            BEGIN
                INSERT INTO TB_CLIENTE(NOME, CPF, EMAIL, RENDA_MENSAL, TELEFONE)
                VALUES (@NOME,@CPF,@EMAIL,@RENDA_MENSAL,@TELEFONE)

                SET @ID_CLIENTE = (SELECT ID_CLIENTE FROM TB_CLIENTE WHERE CPF = @CPF)

                INSERT INTO TB_CONTA(ID_CLIENTE, SALDO, STATUS)
                VALUES (@ID_CLIENTE,0.0,'BLOQUEADA')
            END
            ELSE
                RAISERROR('CLIENTE JÁ EXISTENTE',16,1)
        end

        FETCH C_CLIENTE INTO @ID_SOLICITACAO,@NOME,@CPF,@EMAIL,@RENDA_MENSAL,@TELEFONE,@STATUS;
    end
    CLOSE C_CLIENTE
    DEALLOCATE C_CLIENTE
end

INSERT INTO TB_SOLICITACAO_ABERTURA_CONTA(NOME, CPF, EMAIL, RENDA_MENSAL, TELEFONE)
VALUES ('TONHO',10020024526,'TONHO@GMAIL.COM',1000,'999220843')

UPDATE TB_SOLICITACAO_ABERTURA_CONTA
SET EMAIL = 'toin@gmail.com'
WHERE ID_SOLICITACAO = 1

SELECT * FROM  TB_SOLICITACAO_ABERTURA_CONTA

UPDATE TB_SOLICITACAO_ABERTURA_CONTA
SET STATUS = 'APROVADA'
WHERE ID_SOLICITACAO = 2

SELECT * FROM TB_CLIENTE



SELECT * FROM TB_CONTA









