CREATE DATABASE EX04;

USE EX04

--1
CREATE TABLE TB_CLIENTE
(
    MATRICULA INT,
    NOME      VARCHAR(40),
    TELEFONE  VARCHAR(10)
)

--2
CREATE OR ALTER PROCEDURE SP_INCLUI_CLIENTE(@MATRICULA INT,@NOME VARCHAR(40), @TELEFONE VARCHAR(10))
AS
BEGIN
    INSERT INTO TB_CLIENTE(MATRICULA, NOME, TELEFONE)
    VALUES(@MATRICULA,@NOME,@TELEFONE)
end

--3
CREATE OR ALTER PROCEDURE SP_ALTERA_CLIENTE(@MATRICULA INT,@NOME VARCHAR(40), @TELEFONE VARCHAR(10))
AS
BEGIN
    UPDATE TB_CLIENTE
    SET NOME = @NOME,TELEFONE = @TELEFONE
    WHERE MATRICULA = @MATRICULA
end

--4
CREATE OR ALTER PROCEDURE SP_REMOVE_CLIENTE(@MATRICULA INT)
AS
BEGIN
    DELETE TB_CLIENTE
    WHERE MATRICULA = @MATRICULA
end

--5
CREATE OR ALTER PROCEDURE SP_ALTERA_CLIENTE(@MATRICULA INT,@NOME VARCHAR(40), @TELEFONE VARCHAR(10))
AS
BEGIN
    UPDATE TB_CLIENTE
    SET NOME     = ISNULL(@NOME, NOME),
        TELEFONE = ISNULL(@TELEFONE, TELEFONE)
    WHERE MATRICULA = @MATRICULA
end












EXEC SP_INCLUI_CLIENTE 1,'MARCOS',99220843;

EXEC SP_ALTERA_CLIENTE 1,'VINICIUS',7999220843;

EXEC SP_REMOVE_CLIENTE 1;

SELECT * FROM TB_CLIENTE;




