CREATE DATABASE CURSORES01

USE CURSORES01

--1
CREATE TABLE TB_ALUNO(
	MATRICULA INT PRIMARY KEY,
	NOME VARCHAR(60),
	DT_NASCIMENTO DATETIME
)


CREATE PROCEDURE SP_ADCIONAR_ALUNO(@MATRICULA INT, @NOME VARCHAR(60), @DT_NASCIMENTO DATETIME)
AS
BEGIN
	INSERT INTO TB_ALUNO(MATRICULA,NOME,DT_NASCIMENTO)
	VALUES(@MATRICULA,@NOME,@DT_NASCIMENTO)
END

EXEC SP_ADCIONAR_ALUNO 4,'ROBERT','19950706'

SELECT * FROM TB_ALUNO

--2
--DECLARA AS VARIAVEIS QUE SERÃO USADAS
DECLARE @MATRICULA INT, @NOME VARCHAR(60), @DT_NASCIMENTO DATETIME;
DECLARE @TOTAL INT = 0

--DECLARAR O CURSOR 
DECLARE ALUNO_CURSOR CURSOR FOR
SELECT MATRICULA, NOME, DT_NASCIMENTO
FROM TB_ALUNO;

--ABRINDO O CURSOR
OPEN ALUNO_CURSOR;

--LENDO A PRIMEIRA LINHA 
FETCH NEXT FROM ALUNO_CURSOR INTO @MATRICULA, @NOME, @DT_NASCIMENTO;

--IMPRIMINDO O CABEÇALHO
PRINT 'ALUNOS MATRICULADOS';
PRINT 'MATRICULA       NOME           DATA NASCIMENTO';
PRINT '------------------------------------------------';

--PERCORRENDO TODAS AS LINHAS DO CURSOR
WHILE @@FETCH_STATUS = 0
BEGIN
	--EXIBINDO O ALUNO ATUAL 
	PRINT CAST(@MATRICULA AS VARCHAR(5)) + '        ' + @NOME + '      ' + CONVERT(VARCHAR(10),@DT_NASCIMENTO, 103);

	--CONTANDO O TOTAL DE ALUNOS
	SET @TOTAL = @TOTAL + 1;

	--LENDO A PROXIMA LINHA
	FETCH NEXT FROM ALUNO_CURSOR INTO @MATRICULA, @NOME, @DT_NASCIMENTO;
END

--FECHANDO O CURSOR
CLOSE ALUNO_CURSOR;

--LIBERANDO OS RECURSOSDO CURSOR
DEALLOCATE ALUNO_CURSOR;

-- IMPRIMINDO O TOTAL DE ALUNOS
PRINT '------------------------------------------------';
PRINT 'TOTAL DE ALUNOS: ' + CAST(@total AS VARCHAR(5));













