CREATE DATABASE AVI;

USE AVI;

CREATE TABLE TB_PLANO (
   ID_PLANO INT NOT NULL PRIMARY KEY,
   NM_PLANO VARCHAR(100) NOT NULL,
   VALOR_PLANO NUMERIC(10,2)
)

CREATE TABLE TB_CLIENTE (
   ID_CLIENTE INT NOT NULL PRIMARY KEY,
   NM_CLIENTE VARCHAR(100) NOT NULL,
   ID_PLANO INT NOT NULL REFERENCES TB_PLANO (ID_PLANO),
   MELHOR_DATA INT NOT NULL CHECK(MELHOR_DATA IN (5,10,15)),
   STATUS VARCHAR(10) NOT NULL DEFAULT('ATIVO'),
   CONSTRAINT CK_STATUS CHECK(STATUS IN ('ATIVO','INATIVO'))
)

CREATE TABLE TB_PARAMETRO (
   NM_PARAMETRO VARCHAR(100) NOT NULL UNIQUE,
   VALOR_PARAMETRO NUMERIC(10,2) NOT NULL
)

INSERT INTO TB_PARAMETRO VALUES ('MULTA_ATRASO', 4.00),
                                 ('JUROS_MORA_DIA', 0.50)
CREATE TABLE TB_BOLETO (
   ID_BOLETO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   ANO INT NOT NULL,
   MES INT NOT NULL,
   ID_CLIENTE INT NOT NULL REFERENCES TB_CLIENTE (ID_CLIENTE),
   NM_CLIENTE VARCHAR(100) NOT NULL,
   ID_PLANO INT NOT NULL REFERENCES TB_PLANO (ID_PLANO),
   NM_PLANO VARCHAR(100) NOT NULL,
   DATA_GERACAO DATETIME NOT NULL,
   DATA_VENCIMENTO DATETIME NOT NULL,
   DATA_PAGAMENTO DATETIME NULL,
   VALOR_PLANO  NUMERIC(10,2) NOT NULL,
   MULTA_ATRASO NUMERIC(10,2) NULL,
   JUROS_MORA   NUMERIC (10,2) NULL,
   VALOR_TOTAL NUMERIC(10,2) NULL,
   UNIQUE (ANO, MES, ID_CLIENTE)
)

----
INSERT INTO TB_PLANO VALUES (1,'100Mb', 80.00),
                            (2,'200Mb', 120.00),
			    (3,'300Mb', 150.00)

INSERT INTO TB_CLIENTE VALUES(10,'JOAO',1, 5, 'ATIVO')
INSERT INTO TB_CLIENTE VALUES(20,'PATRICIA',2,10, 'ATIVO')

SELECT * FROM TB_PARAMETRO
SELECT * FROM TB_PLANO
SELECT * FROM TB_CLIENTE
SELECT * FROM TB_BOLETO


--1
CREATE PROCEDURE SP_GERAR_BOLETOS(@ANO INT, @MES INT)
AS
BEGIN

end