CREATE DATABASE EX08;

USE EX08;

CREATE TABLE TB_CARGO (
 CD_CARGO INT NOT NULL PRIMARY KEY,
 NM_CARGO VARCHAR(50) NOT NULL
)

INSERT INTO TB_CARGO VALUES(1, 'ANALISTA')
INSERT INTO TB_CARGO VALUES(2, 'DBA')
INSERT INTO TB_CARGO VALUES(3, 'PROGRAMADOR')


CREATE TABLE TB_ESCOLARIDADE (
  CD_ESCOLARIDADE INT NOT NULL PRIMARY KEY,
  NM_ESCOLARIDADE VARCHAR(50) NOT NULL
)

INSERT INTO TB_ESCOLARIDADE VALUES (1, 'N�VEL M�DIO')
INSERT INTO TB_ESCOLARIDADE VALUES (2, 'N�VEL SUPERIOR')
INSERT INTO TB_ESCOLARIDADE VALUES (3, 'P�S-GRADUA��O')

CREATE TABLE TB_FAIXASALARIAL (
  CD_CARGO INT NOT NULL,
  CD_ESCOLARIDADE INT NOT NULL,
  MENOR_VALOR  NUMERIC(10,2) NOT NULL,
  MAIOR_VALOR  NUMERIC(10,2) NOT NULL
  PRIMARY KEY (CD_CARGO, CD_ESCOLARIDADE)
)

INSERT INTO TB_FAIXASALARIAL VALUES(1,1,900.0, 1100.0)
INSERT INTO TB_FAIXASALARIAL VALUES(1,2,1200.0, 1300.0)
INSERT INTO TB_FAIXASALARIAL VALUES(1,3,1400.0, 1500.0)

INSERT INTO TB_FAIXASALARIAL VALUES(2,1,600.0, 700.0)
INSERT INTO TB_FAIXASALARIAL VALUES(2,2,800.0, 1000.0)
INSERT INTO TB_FAIXASALARIAL VALUES(2,3,1100.0, 1500.0)

INSERT INTO TB_FAIXASALARIAL VALUES(3,1,1300.0, 1500.0)
INSERT INTO TB_FAIXASALARIAL VALUES(3,2,2000.0, 2500.0)
INSERT INTO TB_FAIXASALARIAL VALUES(3,3,3000.0, 3500.0)


CREATE TABLE TB_FUNCIONARIO (
  MATRICULA INT NOT NULL PRIMARY KEY,
  NOME VARCHAR(30) NOT NULL,
  CD_CARGO INT REFERENCES TB_CARGO(CD_CARGO),
  CD_ESCOLARIDADE INT REFERENCES TB_ESCOLARIDADE(CD_ESCOLARIDADE),
  SALARIO NUMERIC (10,2)
)

CREATE TABLE TB_LOG_FUNCIONARIO (
   MATRICULA INT,
   ERRO VARCHAR(200),
   DATA_ERRO DATETIME
)


CREATE PROCEDURE SP_CHECARSALARIO(@CODCARGO INT,@CodEscolaridade INT,@SALARIO DECIMAL(10,2),@BOLEANO INT OUTPUT)
AS
BEGIN
    DECLARE @MAX DECIMAL(10,2);
    DECLARE @MIN DECIMAL(10,2);

    SELECT @MIN = MENOR_VALOR,
           @MAX = MAIOR_VALOR
    FROM TB_FAIXASALARIAL
    WHERE CD_CARGO = @CODCARGO
    AND CD_ESCOLARIDADE = @CodEscolaridade

    IF @SALARIO <= @MAX AND @SALARIO >= @MIN
    BEGIN
        SET @BOLEANO = 1;
        PRINT 'SALARIO CERTO!';
    END
    ELSE
    BEGIN
        SET @BOLEANO = 0;
        PRINT 'SALARIO ERRADO!'
    END
END


CREATE PROCEDURE CHECARFUNCIONARIO
AS
BEGIN
    DECLARE @MATRICULA INT;
    DECLARE @CARGO INT;
    DECLARE @ESCOLARIDADE INT;
    DECLARE @SALARIO NUMERIC(10,2);
    DECLARE @BOLEANO INT;

    DECLARE FUNCIONARIO_CURSOR CURSOR FOR
        SELECT  MATRICULA,
                CD_CARGO,
                CD_ESCOLARIDADE,
                SALARIO
        FROM TB_FUNCIONARIO;

    OPEN FUNCIONARIO_CURSOR;

    FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @MATRICULA, @CARGO,@ESCOLARIDADE, @SALARIO;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        EXEC SP_CHECARSALARIO @CARGO,@ESCOLARIDADE,@SALARIO,@BOLEANO OUTPUT;
        IF @BOLEANO = 0
        BEGIN
            INSERT INTO TB_LOG_FUNCIONARIO (MATRICULA,ERRO,DATA_ERRO)
            VALUES (@MATRICULA,'SALARIO ERRADO',GETDATE());
        END

        FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @MATRICULA, @CARGO, @ESCOLARIDADE, @SALARIO;
    END

    CLOSE FUNCIONARIO_CURSOR;
    DEALLOCATE FUNCIONARIO_CURSOR;

END

DECLARE @BOL INT;
EXEC SP_CHECARSALARIO 1,1,5000,@BOL;
PRINT @BOL

-- Fora do Intervalo
INSERT INTO TB_FUNCIONARIO VALUES(1,'JOAO',1,1, 800.00)
-- Dentro do Intervalo
INSERT INTO TB_FUNCIONARIO VALUES(2,'PEDRO',2,3,1200.0)

EXEC CHECARFUNCIONARIO;

SELECT * FROM TB_LOG_FUNCIONARIO;