CREATE DATABASE PROVA02_2023

USE PROVA02_2023

drop database  PROVA02_2023

CREATE TABLE TB_PESSOA(
    MATRICULA INT NOT NULL PRIMARY KEY IDENTITY (1000,1),
    NOME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL  UNIQUE,
    FUNCAO VARCHAR(45) NOT NULL
);

ALTER TABLE TB_PESSOA
ADD CONSTRAINT FUNCAO CHECK (FUNCAO IN ('aluno','professor'))

CREATE TABLE TB_PROJETO(
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NULL,
    COD_PROJETO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(45) NOT NULL UNIQUE,
    DESCRICAO VARCHAR(100) NOT NULL
);

CREATE TABLE TB_PROJETO_PESSOA(
    MATRICULA INT NOT NULL,
    COD_PROJETO INT NOT NULL,
    FOREIGN KEY (MATRICULA)REFERENCES TB_PESSOA(MATRICULA),
    FOREIGN KEY (COD_PROJETO)REFERENCES TB_PROJETO(COD_PROJETO),
    PRIMARY KEY(MATRICULA,COD_PROJETO)
);

CREATE TABLE TB_PRODUTO(
    COD_PRODUTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    TIPO VARCHAR(10) NOT NULL CHECK (TIPO in ('artigo', 'relatótio')),
    COD_PROJETO INT NOT NULL,
    FOREIGN KEY (COD_PROJETO)REFERENCES TB_PROJETO(COD_PROJETO)
);

-- Inserindo dados na tabela TB_PESSOA
INSERT INTO TB_PESSOA (NOME, EMAIL, FUNCAO) VALUES ('João Silva', 'joao.silva@example.com', 'aluno');
INSERT INTO TB_PESSOA (NOME, EMAIL, FUNCAO) VALUES ('Maria Oliveira', 'maria.oliveira@example.com', 'professor');
INSERT INTO TB_PESSOA (NOME, EMAIL, FUNCAO) VALUES ('Carlos Santos', 'carlos.santos@example.com', 'aluno');
INSERT INTO TB_PESSOA (NOME, EMAIL, FUNCAO) VALUES ('Ana Souza', 'ana.souza@example.com', 'professor');

-- Inserindo dados na tabela TB_PROJETO
INSERT INTO TB_PROJETO (DATA_INICIO, NOME, DESCRICAO) VALUES ('2025-01-01', 'Projeto Alpha', 'Descrição do Projeto Alpha');
INSERT INTO TB_PROJETO (DATA_INICIO, DATA_FIM, NOME, DESCRICAO) VALUES ('2024-06-01', '2024-12-31', 'Projeto Beta', 'Descrição do Projeto Beta');
INSERT INTO TB_PROJETO (DATA_INICIO, DATA_FIM, NOME, DESCRICAO) VALUES ('2023-03-15', '2023-11-30', 'Projeto Gamma', 'Descrição do Projeto Gamma');
INSERT INTO TB_PROJETO (DATA_INICIO, NOME, DESCRICAO) VALUES ('2025-02-01', 'Projeto Delta', 'Descrição do Projeto Delta');

-- Inserindo dados na tabela TB_PROJETO_PESSOA
INSERT INTO TB_PROJETO_PESSOA (MATRICULA, COD_PROJETO) VALUES (1000, 1);  -- João Silva no Projeto Alpha
INSERT INTO TB_PROJETO_PESSOA (MATRICULA, COD_PROJETO) VALUES (1001, 1);  -- Maria Oliveira no Projeto Alpha
INSERT INTO TB_PROJETO_PESSOA (MATRICULA, COD_PROJETO) VALUES (1002, 2);  -- Carlos Santos no Projeto Beta
INSERT INTO TB_PROJETO_PESSOA (MATRICULA, COD_PROJETO) VALUES (1003, 3);  -- Ana Souza no Projeto Gamma

-- Inserindo dados na tabela TB_PRODUTO
INSERT INTO TB_PRODUTO (NOME, DESCRICAO, TIPO, COD_PROJETO) VALUES ('Artigo 1', 'Descrição do Artigo 1', 'artigo', 1);  -- Produto do Projeto Alpha
INSERT INTO TB_PRODUTO (NOME, DESCRICAO, TIPO, COD_PROJETO) VALUES ('Relatório 1', 'Descrição do Relatório 1', 'relatótio', 2);  -- Produto do Projeto Beta
INSERT INTO TB_PRODUTO (NOME, DESCRICAO, TIPO, COD_PROJETO) VALUES ('Artigo 2', 'Descrição do Artigo 2', 'artigo', 3);  -- Produto do Projeto Gamma
-- Projeto Delta não possui produtos ainda

--2
--A
SELECT
    NOME,
    DESCRICAO,
    DATA_INICIO
FROM
    TB_PROJETO
WHERE
    DATA_FIM IS NOT NULL
ORDER BY
    DATA_INICIO DESC;

--B
SELECT
    TP.NOME,
    T.NOME,
    T.TIPO
FROM
    TB_PROJETO TP
LEFT JOIN
    TB_PRODUTO T on TP.COD_PROJETO = T.COD_PROJETO

--C
SELECT
    T.MATRICULA,
    T.NOME,
    T.FUNCAO
FROM
    TB_PROJETO_PESSOA TPP
JOIN
    TB_PESSOA T on T.MATRICULA = TPP.MATRICULA
WHERE
    TPP.COD_PROJETO = 1

--D
SELECT
    TP.NOME,
    T.NOME,
    T.TIPO
FROM
    TB_PROJETO TP
LEFT JOIN
    TB_PRODUTO T on TP.COD_PROJETO = T.COD_PROJETO
WHERE
    TP.DATA_FIM IS NOT NULL AND T.COD_PRODUTO IS NULL