CREATE DATABASE EX06;

USE EX06;

CREATE TABLE TB_FUNCIONARIO(
	MATRICULA	INT IDENTITY(1,1)	PRIMARY KEY  NOT NULL,
	NOME		VARCHAR(60)	NOT NULL,
	TELEFONE	VARCHAR(11),
	ENDERECO	VARCHAR(60),
	SALARIO		DECIMAL(10,2),
	PENDENCIA	VARCHAR(20)
)

CREATE PROCEDURE SP_ADCIONAR_FUNCIONARIO(@NOME VARCHAR(60),@TELEFONE VARCHAR(11),@ENDERECO VARCHAR(60),@SALARIO DECIMAL(10,2))
AS
BEGIN
	INSERT INTO TB_FUNCIONARIO(NOME,TELEFONE,ENDERECO,SALARIO)
	VALUES(@NOME,@TELEFONE,@ENDERECO,@SALARIO)
END

EXEC SP_ADCIONAR_FUNCIONARIO 'JOAO','999999','RUAS DAS PICOS',10000;

CREATE OR ALTER PROCEDURE SP_PENDENCIA
AS
BEGIN
	
	DECLARE @MATRICULA INT;
	DECLARE @TELEFONE VARCHAR(11);
	DECLARE @ENDERECO VARCHAR(60);
	DECLARE @PENDENCIA VARCHAR(20);
	DECLARE @SALARIO DECIMAL(10,2);

	
	DECLARE FUNCIONARIO_CURSOR CURSOR FOR
	SELECT MATRICULA,TELEFONE,ENDERECO,SALARIO,PENDENCIA
	FROM TB_FUNCIONARIO;

	OPEN FUNCIONARIO_CURSOR;

	FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @MATRICULA,@TELEFONE,@ENDERECO,@SALARIO;
	
	WHILE @@FETCH_STATUS = 0
	BEGIN 
		SET @PENDENCIA = 'SEM PENDENCIA'
		IF @TELEFONE IS NULL OR @ENDERECO IS NULL OR @SALARIO IS NULL
		BEGIN 
			SET @PENDENCIA = 'EXISTE PENDENCIA'
		END
		UPDATE TB_FUNCIONARIO
		SET PENDENCIA = @PENDENCIA
		WHERE MATRICULA = @MATRICULA
		FETCH NEXT FROM FUNCIONARIO_CURSOR INTO @MATRICULA,@TELEFONE,@ENDERECO,@SALARIO;
	END
	CLOSE FUNCIONARIO_CURSOR;
    DEALLOCATE FUNCIONARIO_CURSOR;
END

EXEC SP_PENDENCIA;
