CREATE DATABASE EX05
USE EX05
CREATE OR ALTER PROCEDURE SP_IMPOSTO_DE_RENDA(@RENDA DECIMAL(10,2), @IMPOSTO DECIMAL(10,2) OUTPUT)
AS 
BEGIN 
	DECLARE @ALIQUOTA DECIMAL(10,2)
	DECLARE @DEDUZIR DECIMAL(10,2)
	IF @RENDA < 1372.81 
	BEGIN 
		SET @ALIQUOTA = 0;
		SET @DEDUZIR = 0;
	END
	ELSE IF @RENDA < 2743.25
	BEGIN
		SET @ALIQUOTA = 0.15;
		SET @DEDUZIR = 205.92;
	END
	ELSE
	BEGIN
		SET @ALIQUOTA = 0.275;
		SET @DEDUZIR = 548.82;
	END
	SET @IMPOSTO = (@RENDA * @ALIQUOTA) - @DEDUZIR
END

DECLARE @IMPOSTO NUMERIC(10,2)
EXEC SP_IMPOSTO_DE_RENDA 2000, @IMPOSTO OUTPUT
PRINT @IMPOSTO
