USE LAB01;

CREATE TABLE TB_FUNCIONARIO(
	MATRICULA		INT					NOT NULL PRIMARY KEY,
	CPF				VARCHAR(11)			NOT NULL,
	NOME			VARCHAR(60)			NOT NULL,
	CODEP			INT,
	FOREIGN KEY	(CODEP) REFERENCES TB_DEPARTAMENTO(CD_DEPARTAMENTO)
)

CREATE TABLE TELEFONE (
    ID 				INT 				PRIMARY KEY,
    Numero 			VARCHAR(15)			NOT NULL,
    FuncionarioID 	INT,
    FOREIGN KEY (FuncionarioID) REFERENCES TB_FUNCIONARIO(MATRICULA)
);

CREATE TABLE TB_DEPARTAMENTO(
	CD_DEPARTAMENTO		INT				NOT NULL PRIMARY KEY,
	NM_DEPARTAMENTO		VARCHAR(30)		NOT NULL,	
);

CREATE TABLE TB_CATPROBLEMA(
	CD_CATEGORIA		INT				NOT NULL PRIMARY KEY,
	DESCRICAO			VARCHAR(60)		NOT NULL
);

CREATE TABLE TB_TERCEIRIZADOS(
	MATRICULA			INT				NOT NULL PRIMARY KEY,
	NOME				VARCHAR(30)		NOT NULL
);

CREATE TABLE FAZ_SOLICITACAO(
	ID					INT				PRIMARY KEY,
	STATUS 				VARCHAR(20) 	DEFAULT 'Em Aberto' CHECK (Status IN ('Em Aberto', 'Fechado', 'Cancelado')),
	DT_FECHAMENTO		DATETIME 		NULL DEFAULT NULL,
	DT_ABERTURA			DATETIME		NOT NULL,
	DS_PROBLEMA			VARCHAR(60)		NOT NULL,
	ID_FUN				INT,
	ID_DEP				INT,
	FOREIGN KEY (ID_FUN) REFERENCES TB_FUNCIONARIO(MATRICULA),
	FOREIGN KEY (ID_DEP) REFERENCES TB_DEPARTAMENTO(CD_DEPARTAMENTO)
);

CREATE TABLE ATENDE(
	ID				INT			PRIMARY KEY,
	ID_CAT			INT,
	ID_TER			INT,
	FOREIGN KEY (ID_CAT) REFERENCES TB_CATPROBLEMA(CD_CATEGORIA),
	FOREIGN KEY (ID_TER) REFERENCES TB_TERCEIRIZADOS(MATRICULA)
)
